OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Models/Customer.cs
// <copyright file="Customer.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrinkShop.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// customer web class.
    /// </summary>
    public class Customer
    {
        /// <summary>
        /// Gets or sets of id.
        /// </summary>
        [Display(Name = "Customer ID")]
        [Required]
        public int? ID { get; set; }

        /// <summary>
        /// Gets or sets of name.
        /// </summary>
        [Display(Name = "Customer Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets of address.
        /// </summary>
        [Display(Name = "Customer Address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets of age.
        /// </summary>
        [Display(Name = "Age")]
        public int Age { get; set; }

        /// <summary>
        /// Gets or sets of phone.
        /// </summary>
        [Display(Name = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets of purchase id.
        /// </summary>
        [Display(Name = "purchaseID")]
        public int? PurchaseID { get; set; }
    }
}

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Models/CustomerListViewModel.cs
// <copyright file="CustomerListViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrinkShop.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// CustomerviewModel class.
    /// </summary>
    public class CustomerListViewModel
    {
        /// <summary>
        /// Gets or sets List of customer databese.
        /// </summary>
        public List<Customer> ListOfCustomers { get; set; }

        /// <summary>
        /// Gets or sets of Edited customer.
        /// </summary>
        public Customer EditedCustomer { get; set; }
    }
}

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Controllers/CustomersController.cs
// <copyright file="CustomersController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrinkShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using DrinkShop.Logic;
    using DrinkShop.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Customer Controller class.
    /// </summary>
    public class CustomersController : Controller
    {
        private IPeopleLogic logic;
        private IMapper mapper;
        private CustomerListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomersController"/> class.
        /// Constructor of customercontroller.
        /// </summary>
        /// <param name="logic">Ipeoplelogic.</param>
        /// <param name="mapper">Automapper.</param>
        public CustomersController(IPeopleLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new CustomerListViewModel();
            this.vm.EditedCustomer = new Models.Customer();

            var customers = logic.GetAllCustomer();
            this.vm.ListOfCustomers = mapper.Map<IList<Data.Drinks.Customer>, List<Models.Customer>>(customers);
        }

        /// <summary>
        /// Index of customers.
        /// </summary>
        /// <returns>customerindex vm.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("CustomerIndex", this.vm);
        }

        /// <summary>
        /// Details of one customer.
        /// </summary>
        /// <param name="id">id of customer.</param>
        /// <returns>Details.</returns>
        public IActionResult Details(int id)
        {
            return this.View("CustomersDetails", this.GetCustomerModel(id));
        }

        /// <summary>
        /// Remove a customer.
        /// </summary>
        /// <param name="id">id of the customer.</param>
        /// <returns>Redirect action index.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete Fail";
            if (this.logic.DeleteCust(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit customer.
        /// </summary>
        /// <param name="id">id of the cutomer.</param>
        /// <returns>customerindex.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedCustomer = this.GetCustomerModel(id);
            return this.View("CustomerIndex", this.vm);
        }

        /// <summary>
        /// Edit method for adding a customer.
        /// </summary>
        /// <param name="customer">model customer.</param>
        /// <param name="editAction">edit action.</param>
        /// <returns>True if can edited.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Customer customer, string editAction)
        {
            if (this.ModelState.IsValid && customer != null)
            {
                Data.Drinks.Customer customerEntity = this.mapper.Map<Models.Customer, Data.Drinks.Customer>(customer);
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        customerEntity.CostumerID = null;
                        this.logic.CreateCustomer(customerEntity);
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "AddCustomer FAIL: " + ex.Message;
                    }
                }
                else
                {
                    if (!this.logic.ChangeCustomer((int)customer.ID, customer.Name, customer.Address, customer.Phone, customer.Age))
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedCustomer = customer;
                return this.View("CustomerIndex", this.vm);
            }
        }

        private Models.Customer GetCustomerModel(int id)
        {
            Data.Drinks.Customer oneCustomer = this.logic.GetCustomerById(id);
            return this.mapper.Map<Data.Drinks.Customer, Models.Customer>(oneCustomer);
        }
    }
}

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Views/Customers/CustomerIndex.cshtml
@model DrinkShop.Web.Models.CustomerListViewModel

@{
    ViewData["Title"] = "CustomerIndex";
}

<h2>Customer Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("CustomersEdit", Model.EditedCustomer)

@await Html.PartialAsync("CustomerList", Model.ListOfCustomers)

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Views/Customers/CustomerList.cshtml
@model IEnumerable<DrinkShop.Web.Models.Customer>

    <h2>CustomerList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
	{
<table>
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().Name)</th>
        <th>@Html.DisplayNameFor(m => m.First().PurchaseID)</th>
        <th>@Html.DisplayNameFor(m => m.First().Address)</th>
        <th>@Html.DisplayNameFor(m => m.First().Age)</th>
        <th>@Html.DisplayNameFor(m => m.First().Phone)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Modify</th>

    </tr>
    @foreach (var customer in Model)
    {
<tr>
    <td>@Html.DisplayFor(m => customer.Name)</td>
    <td>@Html.DisplayFor(m => customer.PurchaseID)</td>
    <td>@Html.DisplayFor(m => customer.Address)</td>
    <td>@Html.DisplayFor(m => customer.Age)</td>
    <td>@Html.DisplayFor(m => customer.Phone)</td>
    <td>@Html.ActionLink("[SHOW]", "Details", new { id = customer.ID })</td>
    <td>@Html.ActionLink("[DEL]", "Remove", new { id = customer.ID })</td>
    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = customer.ID })</td>


</tr>
    }

</table>
	}

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Views/Customers/CustomersDetails.cshtml
@model DrinkShop.Web.Models.Customer

@{
    ViewData["Title"] = "CustomerDetails";
}

<h2>Datasheet of one customer</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Address)</td>
        <td>@Html.DisplayFor(m => m.Address)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Age)</td>
        <td>@Html.DisplayFor(m => m.Age)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Phone)</td>
        <td>@Html.DisplayFor(m => m.Phone)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_XLE4EJ/DrinkShop.Web/Views/Customers/CustomersEdit.cshtml
@model DrinkShop.Web.Models.Customer

<h2>CustomerEdit</h2>

@using (Html.BeginForm("Edit", "Customers"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Address)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Address)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Phone)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Phone)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Age)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Age)</div>

    <input type="submit" value="SEND" />
}